language: swift

osx_image: xcode11.3

addons:
  homebrew:
    brewfile: true

before_install:
  - gem install xcpretty-travis-formatter
  - bash run.sh

script:
  - xcodebuild -scheme Fosdem -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=13.3' build test | xcpretty -f `xcpretty-travis-formatter`

after_success:
  - bash <(curl -s https://codecov.io/bash)
