language: swift

osx_image: xcode11.5

addons:
  homebrew:
    update: true
    packages:
      - xcodegen
      - swiftformat

before_install:
  - gem install xcpretty-travis-formatter
  - xcodegen

script:
  - xcodebuild -scheme FOSDEM -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=13.3' build test | xcpretty -f `xcpretty-travis-formatter`

after_success:
  - bash <(curl -s https://codecov.io/bash)
