name: FOSDEM
packages:
  GRDB:
    url: https://github.com/groue/GRDB.swift
    version: 4.9.0
  CrashReporter:
    url: https://github.com/microsoft/plcrashreporter
    branch: master
options:
  createIntermediateGroups: true
  bundleIdPrefix: com.mttcrsp.fosdem
settings:
  SWIFT_TREAT_WARNINGS_AS_ERRORS: 'YES'
  SWIFT_VERSION: '5.1'
targets:
  FOSDEM:
    type: application
    platform: iOS
    deploymentTarget: '10.0'
    sources:
    - Sources
    - Resources
    scheme:
      gatherCoverageData: true
      testTargets:
        - name: Tests
          randomExecutionOrder: true
    dependencies:
    - package: GRDB
    - package: CrashReporter
    prebuildScripts:
    - script: [[ -z "${JSONBIN_SECRET_KEY}" ]] || sed -i "" "s|JSONBIN_SECRET_KEY|$JSONBIN_SECRET_KEY|" Sources/Models/Secret.swift
    postbuildScripts:
    - script: swiftformat .
    settings:
      base:
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: "$(inherited)"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CURRENT_PROJECT_VERSION: 1
        DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
        DEVELOPMENT_TEAM: 3CM92FF2C5
        INFOPLIST_FILE: Resources/Info.plist
        MARKETING_VERSION: 1.0.0
        PRODUCT_BUNDLE_IDENTIFIER: com.mttcrsp.fosdem
        PRODUCT_NAME: "$(TARGET_NAME)"
        PRODUCT_MODULE_NAME: Fosdem
        TARGETED_DEVICE_FAMILY: "1,2"
        VERSIONING_SYSTEM: apple-generic
  Tests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: '10.0'
    sources:
    - Tests
    - Resources/Buildings
    dependencies:
    - target: FOSDEM
    postbuildScripts:
    - script: swiftformat .
    settings:
      INFOPLIST_FILE: Tests/Resources/Info.plist
      ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: "$(inherited)"
      TEST_HOST: "$(BUILT_PRODUCTS_DIR)/FOSDEM.app/FOSDEM"
