name: CI

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Tuist
        run: bash <(curl -Ls https://install.tuist.io)
      - name: Run Tuist
        run: tuist up && tuist generate
      - name: Run unit, snapshot, and UI tests
        run: tuist test -d 'iPhone 8 Plus'
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
