name: CI

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install brew dependencies
        run: brew bundle
      - name: Generate project
        run: make generate_project
      - name: Run unit, snapshot, and UI tests
        run: make test
